/**
 * Données mock pour le suivi de projet industriel 100 MW
 * Hearst Qatar - Project Monitoring Dashboard
 */

import {
  Project,
  Phase,
  RampUpStep,
  ProjectKPIs,
  Blocker,
  ActivityLog,
} from '../types/project';

// ============================================================================
// PROJECT KPIs
// ============================================================================

export const mockProjectKPIs: ProjectKPIs = {
  targetMW: 100,
  installedMW: 72,
  operationalMW: 68,
  totalHashrate: 1020, // PH/s
  pue: 1.08,
  csaProgress: 78,
  capexBudget: 145000000, // $145M
  capexSpent: 98500000, // $98.5M
  opexMonthly: 4200000, // $4.2M/month
  daysToTarget: 45,
  overallProgress: 72,
};

// ============================================================================
// RAMP-UP STEPS
// ============================================================================

export const mockRampUpSteps: RampUpStep[] = [
  {
    id: 'ramp-10',
    targetMW: 10,
    plannedDate: '2024-03-15',
    actualDate: '2024-03-12',
    actualMW: 10.2,
    status: 'done',
    availability72h: 99.8,
    wPerTH: 24.2,
    criticalIncidents: 0,
  },
  {
    id: 'ramp-25',
    targetMW: 25,
    plannedDate: '2024-05-01',
    actualDate: '2024-05-05',
    actualMW: 25.1,
    status: 'done',
    availability72h: 99.5,
    wPerTH: 23.8,
    criticalIncidents: 1,
  },
  {
    id: 'ramp-50',
    targetMW: 50,
    plannedDate: '2024-07-15',
    actualDate: '2024-07-20',
    actualMW: 50.4,
    status: 'done',
    availability72h: 99.2,
    wPerTH: 23.5,
    criticalIncidents: 0,
  },
  {
    id: 'ramp-75',
    targetMW: 75,
    plannedDate: '2024-10-01',
    actualDate: '2024-10-08',
    actualMW: 72,
    status: 'in_progress',
    availability72h: 98.7,
    wPerTH: 23.4,
    criticalIncidents: 2,
  },
  {
    id: 'ramp-100',
    targetMW: 100,
    plannedDate: '2025-02-01',
    status: 'not_started',
  },
];

// ============================================================================
// PROJECT PHASES
// ============================================================================

export const mockPhases: Phase[] = [
  {
    id: 'phase-1',
    title: 'Governance & SPV',
    description: 'Company formation, banking, KYC compliance',
    weight: 5,
    progress: 100,
    status: 'done',
    plannedStartDate: '2023-06-01',
    plannedEndDate: '2023-08-15',
    startDate: '2023-06-01',
    endDate: '2023-08-10',
    owner: 'Legal Team',
    milestones: [
      {
        id: 'ms-1-1',
        name: 'SPV Registration',
        plannedDate: '2023-06-15',
        actualDate: '2023-06-12',
        progress: 100,
        status: 'done',
        owner: 'Legal Team',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-1-2',
        name: 'Bank Accounts Setup',
        plannedDate: '2023-07-15',
        actualDate: '2023-07-20',
        progress: 100,
        status: 'done',
        owner: 'Finance',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-1-3',
        name: 'KYC Completion',
        plannedDate: '2023-08-15',
        actualDate: '2023-08-10',
        progress: 100,
        status: 'done',
        owner: 'Compliance',
        comments: [],
        docs: [],
        blockers: [],
      },
    ],
    docs: [
      {
        id: 'doc-1-1',
        name: 'SPV Registration Certificate',
        url: '/docs/spv-cert.pdf',
        type: 'contract',
        status: 'approved',
        uploadedAt: '2023-06-12',
        uploadedBy: 'Legal Team',
      },
    ],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-2',
    title: 'Energy Deals',
    description: 'PPA negotiation, grid connection, land rights',
    weight: 10,
    progress: 100,
    status: 'done',
    plannedStartDate: '2023-07-01',
    plannedEndDate: '2023-11-30',
    startDate: '2023-07-01',
    endDate: '2023-12-05',
    owner: 'Business Dev',
    milestones: [
      {
        id: 'ms-2-1',
        name: 'LOI Signed',
        plannedDate: '2023-08-01',
        actualDate: '2023-08-01',
        progress: 100,
        status: 'done',
        owner: 'Business Dev',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-2-2',
        name: 'PPA Term Sheet',
        plannedDate: '2023-09-15',
        actualDate: '2023-09-20',
        progress: 100,
        status: 'done',
        owner: 'Business Dev',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-2-3',
        name: 'Grid Connection Agreement',
        plannedDate: '2023-10-30',
        actualDate: '2023-11-10',
        progress: 100,
        status: 'done',
        owner: 'Engineering',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-2-4',
        name: 'Final PPA Signed',
        plannedDate: '2023-11-30',
        actualDate: '2023-12-05',
        progress: 100,
        status: 'done',
        owner: 'Business Dev',
        comments: [],
        docs: [],
        blockers: [],
      },
    ],
    docs: [
      {
        id: 'doc-2-1',
        name: 'Power Purchase Agreement',
        url: '/docs/ppa-final.pdf',
        type: 'ppa',
        status: 'approved',
        uploadedAt: '2023-12-05',
        uploadedBy: 'Business Dev',
      },
      {
        id: 'doc-2-2',
        name: 'Grid Connection Agreement',
        url: '/docs/grid-connection.pdf',
        type: 'contract',
        status: 'approved',
        uploadedAt: '2023-11-10',
        uploadedBy: 'Engineering',
      },
    ],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-3',
    title: 'Site Selection & Studies',
    description: 'Topography, geotechnical, hydrology, network constraints',
    weight: 5,
    progress: 100,
    status: 'done',
    plannedStartDate: '2023-08-01',
    plannedEndDate: '2023-10-15',
    startDate: '2023-08-01',
    endDate: '2023-10-10',
    owner: 'Engineering',
    milestones: [
      {
        id: 'ms-3-1',
        name: 'Site Survey Complete',
        plannedDate: '2023-08-30',
        actualDate: '2023-08-28',
        progress: 100,
        status: 'done',
        owner: 'Engineering',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-3-2',
        name: 'Geotechnical Report',
        plannedDate: '2023-09-30',
        actualDate: '2023-09-25',
        progress: 100,
        status: 'done',
        owner: 'Engineering',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-3-3',
        name: 'Network Feasibility',
        plannedDate: '2023-10-15',
        actualDate: '2023-10-10',
        progress: 100,
        status: 'done',
        owner: 'IT/Network',
        comments: [],
        docs: [],
        blockers: [],
      },
    ],
    docs: [
      {
        id: 'doc-3-1',
        name: 'Geotechnical Study Report',
        url: '/docs/geotech-report.pdf',
        type: 'technical',
        status: 'approved',
        uploadedAt: '2023-09-25',
        uploadedBy: 'Engineering',
      },
    ],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-4',
    title: 'Permits & Compliance',
    description: 'Environmental, urban planning, HSE, fire safety, insurance',
    weight: 8,
    progress: 95,
    status: 'in_progress',
    plannedStartDate: '2023-09-01',
    plannedEndDate: '2024-02-28',
    startDate: '2023-09-01',
    owner: 'Compliance',
    milestones: [
      {
        id: 'ms-4-1',
        name: 'Environmental Permit',
        plannedDate: '2023-11-15',
        actualDate: '2023-11-20',
        progress: 100,
        status: 'done',
        owner: 'Compliance',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-4-2',
        name: 'Building Permit',
        plannedDate: '2023-12-15',
        actualDate: '2023-12-18',
        progress: 100,
        status: 'done',
        owner: 'Compliance',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-4-3',
        name: 'Fire Safety Certification',
        plannedDate: '2024-01-30',
        actualDate: '2024-02-02',
        progress: 100,
        status: 'done',
        owner: 'HSE',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-4-4',
        name: 'Insurance Finalization',
        plannedDate: '2024-02-28',
        progress: 85,
        status: 'in_progress',
        owner: 'Finance',
        comments: [
          {
            id: 'comment-4-4-1',
            author: 'Finance Team',
            content: 'Awaiting final premium quotes from 2 insurers',
            createdAt: '2024-12-15',
          },
        ],
        docs: [],
        blockers: [],
      },
    ],
    docs: [
      {
        id: 'doc-4-1',
        name: 'Environmental Impact Assessment',
        url: '/docs/eia.pdf',
        type: 'permit',
        status: 'approved',
        uploadedAt: '2023-11-20',
        uploadedBy: 'Compliance',
      },
      {
        id: 'doc-4-2',
        name: 'Building Permit',
        url: '/docs/building-permit.pdf',
        type: 'permit',
        status: 'approved',
        uploadedAt: '2023-12-18',
        uploadedBy: 'Compliance',
      },
    ],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-5',
    title: 'Preliminary Engineering',
    description: 'Site layout, single-line diagrams, grounding, fault analysis',
    weight: 5,
    progress: 100,
    status: 'done',
    plannedStartDate: '2023-10-01',
    plannedEndDate: '2024-01-15',
    startDate: '2023-10-01',
    endDate: '2024-01-12',
    owner: 'Engineering',
    milestones: [
      {
        id: 'ms-5-1',
        name: 'Site Layout Finalized',
        plannedDate: '2023-11-01',
        actualDate: '2023-10-28',
        progress: 100,
        status: 'done',
        owner: 'Engineering',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-5-2',
        name: 'Single-Line Diagram Approved',
        plannedDate: '2023-12-01',
        actualDate: '2023-12-05',
        progress: 100,
        status: 'done',
        owner: 'Electrical',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-5-3',
        name: 'Grounding Study Complete',
        plannedDate: '2024-01-15',
        actualDate: '2024-01-12',
        progress: 100,
        status: 'done',
        owner: 'Electrical',
        comments: [],
        docs: [],
        blockers: [],
      },
    ],
    docs: [
      {
        id: 'doc-5-1',
        name: 'Single-Line Diagram HV/MV/LV',
        url: '/docs/sld.pdf',
        type: 'technical',
        status: 'approved',
        uploadedAt: '2023-12-05',
        uploadedBy: 'Electrical',
      },
    ],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-6',
    title: 'Major Procurement',
    description: 'Transformers, switchgear, cables, containers, cooling',
    weight: 15,
    progress: 88,
    status: 'in_progress',
    plannedStartDate: '2023-11-01',
    plannedEndDate: '2024-06-30',
    startDate: '2023-11-01',
    owner: 'Procurement',
    milestones: [
      {
        id: 'ms-6-1',
        name: 'Transformers Ordered',
        plannedDate: '2023-12-15',
        actualDate: '2023-12-10',
        progress: 100,
        status: 'done',
        owner: 'Procurement',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-6-2',
        name: 'Switchgear Delivered',
        plannedDate: '2024-03-01',
        actualDate: '2024-03-15',
        progress: 100,
        status: 'done',
        owner: 'Procurement',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-6-3',
        name: 'Mining Containers (Batch 1-3)',
        plannedDate: '2024-04-30',
        actualDate: '2024-05-10',
        progress: 100,
        status: 'done',
        owner: 'Procurement',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-6-4',
        name: 'Mining Containers (Batch 4)',
        plannedDate: '2024-12-15',
        progress: 65,
        status: 'at_risk',
        owner: 'Procurement',
        comments: [
          {
            id: 'comment-6-4-1',
            author: 'Procurement Team',
            content: 'Shipment delayed due to customs hold in transit port',
            createdAt: '2024-12-10',
          },
        ],
        docs: [],
        blockers: [
          {
            id: 'blocker-6-4-1',
            title: 'Customs Clearance Delay',
            description: 'Batch 4 containers stuck at transit port customs',
            severity: 'high',
            eta: '2024-12-28',
            owner: 'Logistics',
            createdAt: '2024-12-08',
            mitigationPlan: 'Expedited customs broker engaged, daily follow-up',
          },
        ],
      },
      {
        id: 'ms-6-5',
        name: 'Cooling Systems Complete',
        plannedDate: '2024-06-30',
        actualDate: '2024-07-05',
        progress: 100,
        status: 'done',
        owner: 'Procurement',
        comments: [],
        docs: [],
        blockers: [],
      },
    ],
    docs: [
      {
        id: 'doc-6-1',
        name: 'Transformer Purchase Order',
        url: '/docs/po-transformers.pdf',
        type: 'contract',
        status: 'approved',
        uploadedAt: '2023-12-10',
        uploadedBy: 'Procurement',
      },
      {
        id: 'doc-6-2',
        name: 'Container Shipping Manifest (Batch 4)',
        url: '/docs/manifest-batch4.pdf',
        type: 'other',
        status: 'pending_review',
        uploadedAt: '2024-12-05',
        uploadedBy: 'Logistics',
      },
    ],
    blockers: [
      {
        id: 'blocker-6-1',
        title: 'Customs Clearance Delay - Batch 4',
        description: 'Mining containers batch 4 held at transit customs',
        severity: 'high',
        eta: '2024-12-28',
        owner: 'Logistics',
        createdAt: '2024-12-08',
        mitigationPlan: 'Expedited customs broker, alternative routing evaluated',
        phaseId: 'phase-6',
        milestoneId: 'ms-6-4',
      },
    ],
    comments: [],
  },
  {
    id: 'phase-7',
    title: 'Logistics & Customs',
    description: 'Factory slots, Incoterms, customs clearance, storage, delivery',
    weight: 5,
    progress: 82,
    status: 'at_risk',
    plannedStartDate: '2024-01-01',
    plannedEndDate: '2024-08-31',
    startDate: '2024-01-01',
    owner: 'Logistics',
    milestones: [
      {
        id: 'ms-7-1',
        name: 'Factory Slots Confirmed',
        plannedDate: '2024-02-01',
        actualDate: '2024-01-28',
        progress: 100,
        status: 'done',
        owner: 'Logistics',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-7-2',
        name: 'All Equipment Cleared Customs',
        plannedDate: '2024-08-31',
        progress: 75,
        status: 'at_risk',
        owner: 'Logistics',
        comments: [
          {
            id: 'comment-7-2-1',
            author: 'Logistics Manager',
            content: 'Batch 4 containers pending customs release',
            createdAt: '2024-12-12',
          },
        ],
        docs: [],
        blockers: [],
      },
    ],
    docs: [],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-8',
    title: 'Civil Works & Utilities',
    description: 'Earthworks, drainage, roads, foundations, fencing, access control',
    weight: 10,
    progress: 100,
    status: 'done',
    plannedStartDate: '2024-01-15',
    plannedEndDate: '2024-06-30',
    startDate: '2024-01-15',
    endDate: '2024-07-05',
    owner: 'Civil',
    milestones: [
      {
        id: 'ms-8-1',
        name: 'Earthworks Complete',
        plannedDate: '2024-03-01',
        actualDate: '2024-02-28',
        progress: 100,
        status: 'done',
        owner: 'Civil',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-8-2',
        name: 'Foundations & Pads Ready',
        plannedDate: '2024-05-01',
        actualDate: '2024-05-10',
        progress: 100,
        status: 'done',
        owner: 'Civil',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-8-3',
        name: 'Fencing & Access Control',
        plannedDate: '2024-06-30',
        actualDate: '2024-07-05',
        progress: 100,
        status: 'done',
        owner: 'Civil',
        comments: [],
        docs: [],
        blockers: [],
      },
    ],
    docs: [],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-9',
    title: 'HV/MV Substation',
    description: 'Substation assembly, switchgear, protections, SCADA/RTU, testing',
    weight: 10,
    progress: 95,
    status: 'in_progress',
    plannedStartDate: '2024-04-01',
    plannedEndDate: '2024-09-30',
    startDate: '2024-04-01',
    owner: 'Electrical',
    milestones: [
      {
        id: 'ms-9-1',
        name: 'Substation Structure Complete',
        plannedDate: '2024-06-01',
        actualDate: '2024-06-05',
        progress: 100,
        status: 'done',
        owner: 'Electrical',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-9-2',
        name: 'Protection Relays Configured',
        plannedDate: '2024-08-15',
        actualDate: '2024-08-20',
        progress: 100,
        status: 'done',
        owner: 'Electrical',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-9-3',
        name: 'SCADA Integration',
        plannedDate: '2024-09-30',
        progress: 85,
        status: 'in_progress',
        owner: 'Controls',
        comments: [
          {
            id: 'comment-9-3-1',
            author: 'Controls Engineer',
            content: 'Final points list validation in progress',
            createdAt: '2024-12-18',
          },
        ],
        docs: [],
        blockers: [],
      },
    ],
    docs: [
      {
        id: 'doc-9-1',
        name: 'Protection Relay Settings',
        url: '/docs/relay-settings.pdf',
        type: 'technical',
        status: 'approved',
        uploadedAt: '2024-08-20',
        uploadedBy: 'Electrical',
      },
    ],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-10',
    title: 'LV Distribution & Backup',
    description: 'Main LV switchboard, MCC, cable trays, UPS/generators',
    weight: 8,
    progress: 90,
    status: 'in_progress',
    plannedStartDate: '2024-05-01',
    plannedEndDate: '2024-10-31',
    startDate: '2024-05-01',
    owner: 'Electrical',
    milestones: [
      {
        id: 'ms-10-1',
        name: 'Main LV Switchboard Installed',
        plannedDate: '2024-07-15',
        actualDate: '2024-07-18',
        progress: 100,
        status: 'done',
        owner: 'Electrical',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-10-2',
        name: 'Cable Trays Complete',
        plannedDate: '2024-09-01',
        actualDate: '2024-09-05',
        progress: 100,
        status: 'done',
        owner: 'Electrical',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-10-3',
        name: 'UPS/Backup Systems Ready',
        plannedDate: '2024-10-31',
        progress: 75,
        status: 'in_progress',
        owner: 'Electrical',
        comments: [],
        docs: [],
        blockers: [],
      },
    ],
    docs: [],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-11',
    title: 'Network & IT',
    description: 'Fiber/microwave, LAN, WiFi, OT/IT segmentation, redundancy',
    weight: 5,
    progress: 92,
    status: 'in_progress',
    plannedStartDate: '2024-06-01',
    plannedEndDate: '2024-11-30',
    startDate: '2024-06-01',
    owner: 'IT/Network',
    milestones: [
      {
        id: 'ms-11-1',
        name: 'Fiber Backbone Installed',
        plannedDate: '2024-08-01',
        actualDate: '2024-07-28',
        progress: 100,
        status: 'done',
        owner: 'IT/Network',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-11-2',
        name: 'LAN/WiFi Operational',
        plannedDate: '2024-10-01',
        actualDate: '2024-10-05',
        progress: 100,
        status: 'done',
        owner: 'IT/Network',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-11-3',
        name: 'Redundancy Failover Tested',
        plannedDate: '2024-11-30',
        progress: 80,
        status: 'in_progress',
        owner: 'IT/Network',
        comments: [],
        docs: [],
        blockers: [],
      },
    ],
    docs: [],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-12',
    title: 'Cooling & Environment',
    description: 'HVAC/immersion/airflow, temp/humidity monitoring, capacity tests',
    weight: 5,
    progress: 100,
    status: 'done',
    plannedStartDate: '2024-05-01',
    plannedEndDate: '2024-09-30',
    startDate: '2024-05-01',
    endDate: '2024-10-02',
    owner: 'Mechanical',
    milestones: [
      {
        id: 'ms-12-1',
        name: 'Cooling Infrastructure Installed',
        plannedDate: '2024-07-31',
        actualDate: '2024-08-05',
        progress: 100,
        status: 'done',
        owner: 'Mechanical',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-12-2',
        name: 'Environmental Monitoring Active',
        plannedDate: '2024-09-15',
        actualDate: '2024-09-18',
        progress: 100,
        status: 'done',
        owner: 'Mechanical',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-12-3',
        name: 'Capacity Tests Passed',
        plannedDate: '2024-09-30',
        actualDate: '2024-10-02',
        progress: 100,
        status: 'done',
        owner: 'Mechanical',
        comments: [],
        docs: [],
        blockers: [],
      },
    ],
    docs: [],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-13',
    title: 'Safety & HSE',
    description: 'Procedures, PPE, work permits, evacuation plans, fire detection',
    weight: 3,
    progress: 100,
    status: 'done',
    plannedStartDate: '2024-06-01',
    plannedEndDate: '2024-10-31',
    startDate: '2024-06-01',
    endDate: '2024-10-28',
    owner: 'HSE',
    milestones: [
      {
        id: 'ms-13-1',
        name: 'HSE Procedures Approved',
        plannedDate: '2024-08-01',
        actualDate: '2024-07-28',
        progress: 100,
        status: 'done',
        owner: 'HSE',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-13-2',
        name: 'Fire Detection Commissioned',
        plannedDate: '2024-10-31',
        actualDate: '2024-10-28',
        progress: 100,
        status: 'done',
        owner: 'HSE',
        comments: [],
        docs: [],
        blockers: [],
      },
    ],
    docs: [
      {
        id: 'doc-13-1',
        name: 'HSE Manual',
        url: '/docs/hse-manual.pdf',
        type: 'hse',
        status: 'approved',
        uploadedAt: '2024-07-28',
        uploadedBy: 'HSE',
      },
    ],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-14',
    title: 'Container/Rack Integration',
    description: 'Placement, power & data cabling, labeling, QA inspection',
    weight: 8,
    progress: 75,
    status: 'in_progress',
    plannedStartDate: '2024-07-01',
    plannedEndDate: '2024-12-31',
    startDate: '2024-07-01',
    owner: 'Operations',
    milestones: [
      {
        id: 'ms-14-1',
        name: 'Containers Batch 1-3 Installed',
        plannedDate: '2024-09-30',
        actualDate: '2024-10-05',
        progress: 100,
        status: 'done',
        owner: 'Operations',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-14-2',
        name: 'Containers Batch 4 Installed',
        plannedDate: '2024-12-31',
        progress: 20,
        status: 'blocked',
        owner: 'Operations',
        comments: [
          {
            id: 'comment-14-2-1',
            author: 'Operations Lead',
            content: 'Waiting for batch 4 containers to clear customs',
            createdAt: '2024-12-15',
          },
        ],
        docs: [],
        blockers: [
          {
            id: 'blocker-14-2-1',
            title: 'Container Delivery Pending',
            description: 'Cannot install batch 4 until customs clearance',
            severity: 'high',
            eta: '2025-01-05',
            owner: 'Logistics',
            createdAt: '2024-12-10',
            mitigationPlan: 'Parallel prep work for container pads complete',
          },
        ],
      },
    ],
    docs: [],
    blockers: [
      {
        id: 'blocker-14-1',
        title: 'Batch 4 Containers Pending',
        description: 'Integration blocked until customs release',
        severity: 'high',
        eta: '2025-01-05',
        owner: 'Logistics',
        createdAt: '2024-12-10',
        mitigationPlan: 'All prep work complete, ready for immediate install upon arrival',
        phaseId: 'phase-14',
      },
    ],
    comments: [],
  },
  {
    id: 'phase-15',
    title: 'Miner Installation',
    description: 'Power, network, firmware, pool config, burn-in',
    weight: 8,
    progress: 72,
    status: 'in_progress',
    plannedStartDate: '2024-08-01',
    plannedEndDate: '2025-01-31',
    startDate: '2024-08-01',
    owner: 'Operations',
    milestones: [
      {
        id: 'ms-15-1',
        name: 'Miners Batch 1-3 Online',
        plannedDate: '2024-10-31',
        actualDate: '2024-11-05',
        progress: 100,
        status: 'done',
        owner: 'Operations',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-15-2',
        name: 'Miners Batch 4 Online',
        plannedDate: '2025-01-31',
        progress: 0,
        status: 'not_started',
        owner: 'Operations',
        comments: [],
        docs: [],
        blockers: [],
      },
    ],
    docs: [],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-16',
    title: 'FAT/SAT Tests',
    description: 'Factory acceptance, site acceptance for key equipment',
    weight: 5,
    progress: 85,
    status: 'in_progress',
    plannedStartDate: '2024-03-01',
    plannedEndDate: '2025-01-15',
    startDate: '2024-03-01',
    owner: 'QA/QC',
    milestones: [
      {
        id: 'ms-16-1',
        name: 'Transformer FAT Passed',
        plannedDate: '2024-04-15',
        actualDate: '2024-04-12',
        progress: 100,
        status: 'done',
        owner: 'QA/QC',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-16-2',
        name: 'Switchgear FAT Passed',
        plannedDate: '2024-05-30',
        actualDate: '2024-06-02',
        progress: 100,
        status: 'done',
        owner: 'QA/QC',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-16-3',
        name: 'All SAT Complete',
        plannedDate: '2025-01-15',
        progress: 70,
        status: 'in_progress',
        owner: 'QA/QC',
        comments: [],
        docs: [],
        blockers: [],
      },
    ],
    docs: [
      {
        id: 'doc-16-1',
        name: 'Transformer FAT Report',
        url: '/docs/fat-transformer.pdf',
        type: 'fat_sat',
        status: 'approved',
        uploadedAt: '2024-04-12',
        uploadedBy: 'QA/QC',
      },
    ],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-17',
    title: 'CSA (Commissioning)',
    description: 'Energization sequence, load tests, protection tests, black-start',
    weight: 10,
    progress: 78,
    status: 'in_progress',
    plannedStartDate: '2024-08-01',
    plannedEndDate: '2025-02-15',
    startDate: '2024-08-01',
    owner: 'Commissioning',
    milestones: [
      {
        id: 'ms-17-1',
        name: 'Initial Energization (10MW)',
        plannedDate: '2024-08-31',
        actualDate: '2024-09-02',
        progress: 100,
        status: 'done',
        owner: 'Commissioning',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-17-2',
        name: 'Protection Relay Tests',
        plannedDate: '2024-10-15',
        actualDate: '2024-10-18',
        progress: 100,
        status: 'done',
        owner: 'Electrical',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-17-3',
        name: '75MW Load Test',
        plannedDate: '2024-12-15',
        progress: 80,
        status: 'in_progress',
        owner: 'Commissioning',
        comments: [
          {
            id: 'comment-17-3-1',
            author: 'Commissioning Lead',
            content: 'Currently at 68MW stable, pushing to 72MW this week',
            createdAt: '2024-12-18',
          },
        ],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-17-4',
        name: '100MW Full Load Test',
        plannedDate: '2025-02-01',
        progress: 0,
        status: 'not_started',
        owner: 'Commissioning',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-17-5',
        name: 'Final CSA Sign-off',
        plannedDate: '2025-02-15',
        progress: 0,
        status: 'not_started',
        owner: 'Commissioning',
        comments: [],
        docs: [],
        blockers: [],
      },
    ],
    docs: [
      {
        id: 'doc-17-1',
        name: 'Initial Energization Report',
        url: '/docs/csa-initial.pdf',
        type: 'csa',
        status: 'approved',
        uploadedAt: '2024-09-02',
        uploadedBy: 'Commissioning',
      },
      {
        id: 'doc-17-2',
        name: 'Protection Test Report',
        url: '/docs/csa-protection.pdf',
        type: 'csa',
        status: 'approved',
        uploadedAt: '2024-10-18',
        uploadedBy: 'Electrical',
      },
    ],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-18',
    title: 'QA Validation',
    description: 'Punch list, corrections, re-tests',
    weight: 3,
    progress: 65,
    status: 'in_progress',
    plannedStartDate: '2024-10-01',
    plannedEndDate: '2025-02-28',
    startDate: '2024-10-01',
    owner: 'QA/QC',
    milestones: [
      {
        id: 'ms-18-1',
        name: 'Punch List Created',
        plannedDate: '2024-11-01',
        actualDate: '2024-11-05',
        progress: 100,
        status: 'done',
        owner: 'QA/QC',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-18-2',
        name: 'Punch Items Resolved',
        plannedDate: '2025-02-28',
        progress: 55,
        status: 'in_progress',
        owner: 'QA/QC',
        comments: [
          {
            id: 'comment-18-2-1',
            author: 'QA Manager',
            content: '22 of 40 punch items closed, 18 remaining',
            createdAt: '2024-12-17',
          },
        ],
        docs: [],
        blockers: [],
      },
    ],
    docs: [],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-19',
    title: 'Ramp-Up',
    description: 'Progressive load increase: 10 -> 25 -> 50 -> 75 -> 100 MW',
    weight: 10,
    progress: 72,
    status: 'in_progress',
    plannedStartDate: '2024-03-01',
    plannedEndDate: '2025-02-28',
    startDate: '2024-03-01',
    owner: 'Operations',
    milestones: [
      {
        id: 'ms-19-1',
        name: '10 MW Achieved',
        plannedDate: '2024-03-15',
        actualDate: '2024-03-12',
        progress: 100,
        status: 'done',
        owner: 'Operations',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-19-2',
        name: '25 MW Achieved',
        plannedDate: '2024-05-01',
        actualDate: '2024-05-05',
        progress: 100,
        status: 'done',
        owner: 'Operations',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-19-3',
        name: '50 MW Achieved',
        plannedDate: '2024-07-15',
        actualDate: '2024-07-20',
        progress: 100,
        status: 'done',
        owner: 'Operations',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-19-4',
        name: '75 MW Achieved',
        plannedDate: '2024-10-01',
        progress: 90,
        status: 'in_progress',
        owner: 'Operations',
        comments: [
          {
            id: 'comment-19-4-1',
            author: 'Operations Lead',
            content: 'Currently at 72MW, targeting 75MW next week',
            createdAt: '2024-12-18',
          },
        ],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-19-5',
        name: '100 MW Achieved',
        plannedDate: '2025-02-01',
        progress: 0,
        status: 'not_started',
        owner: 'Operations',
        comments: [],
        docs: [],
        blockers: [],
      },
    ],
    docs: [],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-20',
    title: 'Performance & Operations',
    description: 'KPIs tracking, energy efficiency, maintenance, ticket management',
    weight: 5,
    progress: 85,
    status: 'in_progress',
    plannedStartDate: '2024-09-01',
    plannedEndDate: '2025-03-31',
    startDate: '2024-09-01',
    owner: 'Operations',
    milestones: [
      {
        id: 'ms-20-1',
        name: 'Monitoring Dashboard Live',
        plannedDate: '2024-10-01',
        actualDate: '2024-09-28',
        progress: 100,
        status: 'done',
        owner: 'IT/Network',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-20-2',
        name: 'NOC Operational 24/7',
        plannedDate: '2024-11-01',
        actualDate: '2024-11-05',
        progress: 100,
        status: 'done',
        owner: 'Operations',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-20-3',
        name: 'Efficiency Target Met (<24 W/TH)',
        plannedDate: '2025-01-31',
        progress: 90,
        status: 'in_progress',
        owner: 'Operations',
        comments: [
          {
            id: 'comment-20-3-1',
            author: 'Operations Manager',
            content: 'Current fleet average: 23.5 W/TH - target achieved',
            createdAt: '2024-12-18',
          },
        ],
        docs: [],
        blockers: [],
      },
    ],
    docs: [],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-21',
    title: 'Documentation & Transfer',
    description: 'As-built drawings, manuals, operations training',
    weight: 3,
    progress: 60,
    status: 'in_progress',
    plannedStartDate: '2024-11-01',
    plannedEndDate: '2025-03-15',
    startDate: '2024-11-01',
    owner: 'Engineering',
    milestones: [
      {
        id: 'ms-21-1',
        name: 'As-Built Drawings Submitted',
        plannedDate: '2025-02-01',
        progress: 50,
        status: 'in_progress',
        owner: 'Engineering',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-21-2',
        name: 'Operations Training Complete',
        plannedDate: '2025-03-01',
        progress: 40,
        status: 'in_progress',
        owner: 'Operations',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-21-3',
        name: 'All Manuals Delivered',
        plannedDate: '2025-03-15',
        progress: 30,
        status: 'in_progress',
        owner: 'Engineering',
        comments: [],
        docs: [],
        blockers: [],
      },
    ],
    docs: [],
    blockers: [],
    comments: [],
  },
  {
    id: 'phase-22',
    title: 'Handover & BAU',
    description: 'SLA finalization, runbooks, preventive maintenance plan',
    weight: 2,
    progress: 40,
    status: 'in_progress',
    plannedStartDate: '2024-12-01',
    plannedEndDate: '2025-03-31',
    startDate: '2024-12-01',
    owner: 'Operations',
    milestones: [
      {
        id: 'ms-22-1',
        name: 'SLA Finalized',
        plannedDate: '2025-02-15',
        progress: 60,
        status: 'in_progress',
        owner: 'Business Dev',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-22-2',
        name: 'Runbooks Published',
        plannedDate: '2025-03-01',
        progress: 45,
        status: 'in_progress',
        owner: 'Operations',
        comments: [],
        docs: [],
        blockers: [],
      },
      {
        id: 'ms-22-3',
        name: 'Preventive Maintenance Plan Active',
        plannedDate: '2025-03-31',
        progress: 25,
        status: 'in_progress',
        owner: 'Operations',
        comments: [],
        docs: [],
        blockers: [],
      },
    ],
    docs: [],
    blockers: [],
    comments: [],
  },
];

// ============================================================================
// GLOBAL BLOCKERS
// ============================================================================

export const mockBlockers: Blocker[] = [
  {
    id: 'blocker-global-1',
    title: 'Customs Clearance Delay - Batch 4 Containers',
    description: 'Mining containers batch 4 (12 units) held at transit port customs due to documentation discrepancy',
    severity: 'high',
    eta: '2024-12-28',
    owner: 'Logistics',
    createdAt: '2024-12-08',
    mitigationPlan: 'Expedited customs broker engaged. Daily follow-up calls. Alternative routing via air freight evaluated for critical components.',
    phaseId: 'phase-6',
    milestoneId: 'ms-6-4',
  },
  {
    id: 'blocker-global-2',
    title: 'Insurance Final Premium Pending',
    description: 'Awaiting final insurance premium quotes from underwriters for operational coverage',
    severity: 'medium',
    eta: '2025-01-05',
    owner: 'Finance',
    createdAt: '2024-12-10',
    mitigationPlan: 'Parallel negotiations with backup insurer. Interim coverage extended.',
    phaseId: 'phase-4',
    milestoneId: 'ms-4-4',
  },
  {
    id: 'blocker-global-3',
    title: 'SCADA Point List Validation',
    description: 'Final validation of SCADA points list pending utility approval',
    severity: 'low',
    eta: '2024-12-22',
    owner: 'Controls',
    createdAt: '2024-12-15',
    mitigationPlan: 'Meeting scheduled with utility on Dec 20. Pre-approved list covers 95% of points.',
    phaseId: 'phase-9',
    milestoneId: 'ms-9-3',
  },
];

// ============================================================================
// ACTIVITY LOG
// ============================================================================

export const mockActivityLog: ActivityLog[] = [
  {
    id: 'log-1',
    action: 'Milestone completed',
    actor: 'Operations Lead',
    timestamp: '2024-12-18T14:30:00Z',
    details: '75MW load test reaching 72MW stable',
    phaseId: 'phase-17',
    milestoneId: 'ms-17-3',
  },
  {
    id: 'log-2',
    action: 'Document uploaded',
    actor: 'Logistics',
    timestamp: '2024-12-15T09:15:00Z',
    details: 'Container Shipping Manifest (Batch 4)',
    phaseId: 'phase-6',
  },
  {
    id: 'log-3',
    action: 'Blocker created',
    actor: 'Logistics Manager',
    timestamp: '2024-12-08T16:45:00Z',
    details: 'Customs Clearance Delay - Batch 4 Containers',
    phaseId: 'phase-6',
  },
  {
    id: 'log-4',
    action: 'Comment added',
    actor: 'QA Manager',
    timestamp: '2024-12-17T11:00:00Z',
    details: '22 of 40 punch items closed',
    phaseId: 'phase-18',
    milestoneId: 'ms-18-2',
  },
  {
    id: 'log-5',
    action: 'Milestone completed',
    actor: 'IT/Network',
    timestamp: '2024-12-10T10:30:00Z',
    details: 'Fiber backbone installation verified',
    phaseId: 'phase-11',
    milestoneId: 'ms-11-1',
  },
  {
    id: 'log-6',
    action: 'Phase completed',
    actor: 'Mechanical Team',
    timestamp: '2024-10-02T15:00:00Z',
    details: 'Cooling & Environment phase fully complete',
    phaseId: 'phase-12',
  },
  {
    id: 'log-7',
    action: 'Document approved',
    actor: 'Commissioning Lead',
    timestamp: '2024-10-18T14:00:00Z',
    details: 'Protection Test Report approved',
    phaseId: 'phase-17',
  },
  {
    id: 'log-8',
    action: 'Ramp-up milestone',
    actor: 'Operations',
    timestamp: '2024-07-20T08:00:00Z',
    details: '50MW target achieved',
    phaseId: 'phase-19',
    milestoneId: 'ms-19-3',
  },
];

// ============================================================================
// FULL PROJECT
// ============================================================================

export const mockProject: Project = {
  id: 'hearst-qatar-100mw',
  name: 'Hearst Qatar 100MW Mining Facility',
  description: 'Industrial-scale Bitcoin mining facility targeting 100MW capacity with state-of-the-art hydro-cooled containers',
  targetMW: 100,
  location: 'Qatar Industrial Zone',
  startDate: '2023-06-01',
  targetDate: '2025-02-28',
  kpis: mockProjectKPIs,
  phases: mockPhases,
  rampUp: mockRampUpSteps,
  docs: [],
  blockers: mockBlockers,
  comments: [],
};

// ============================================================================
// POWER CONSUMPTION HISTORY (for ramp-up chart)
// ============================================================================

export const mockPowerHistory = Array.from({ length: 365 }, (_, i) => {
  const daysAgo = 364 - i;
  const date = new Date(Date.now() - daysAgo * 24 * 60 * 60 * 1000);
  
  // Simulate ramp-up curve
  let mw = 0;
  if (i > 285) mw = 68 + (i - 285) * 0.05; // Post 50MW
  else if (i > 195) mw = 50 + (i - 195) * 0.2; // 50-68MW phase
  else if (i > 135) mw = 25 + (i - 135) * 0.4; // 25-50MW phase
  else if (i > 75) mw = 10 + (i - 75) * 0.25; // 10-25MW phase
  else if (i > 45) mw = (i - 45) * 0.33; // 0-10MW phase
  
  return {
    date: date.toISOString().split('T')[0],
    mw: Math.min(mw, 72), // Cap at current operational
    target: 100,
  };
});

// ============================================================================
// TICKETS / INCIDENTS
// ============================================================================

export const mockTickets = {
  open: 12,
  critical: 2,
  resolved7d: 45,
  avgResolutionHours: 4.2,
};




